### ISSUE TITLE
Add a github link in the top menu

### ISSUE THREAD

**Issue by dervalp** [uxilab/uxi#12]
Really often, as our page lacks documentation I need to see the source code on github.

Could you add a Source Code link pointing to the uxi github repo so I can look at the source (generally of the examples).

**Comment by denisflorkin** [comment]
Do you mean you want one link to the gh repo, or do you mean you want a direct link to the relevant file on gh for each example ?

**Comment by dervalp** [comment]
no one single link to gh repo would do
