### ISSUE TITLE
InputGroup for UXI

### ISSUE THREAD

**Issue by dervalp** [uxilab/uxi#24]
Having the ability to 'stack' element before/after an input.

![image](https://user-images.githubusercontent.com/928792/46996813-38fb0880-d11e-11e8-844f-617749c1bab5.png)

**Comment by denisflorkin** [comment]
There s an input group already, but in this case it s not two inputs, it s an input and something “post-pended” to it.
<Flex /> wil do exactly what you want as its default behaviour
